-- Harvest Local — the labelling rules, captured verbatim.
--
-- `20260904170000` created `state_label_rules` empty on purpose: disclaimer text is quoted statute
-- that gets printed onto food, several of the first captures were truncated, and a partial
-- disclaimer is worse than none. This is the complete pass — all 51 jurisdictions re-read on
-- 2026-09-04, with the disclaimer taken from the quotation marks in the source rather than
-- paraphrased.
--
-- Rules are per PROGRAM, not per state, because two states genuinely differ inside their own
-- borders: New Hampshire's licensed and unlicensed programs carry different disclaimers, and Iowa
-- asks less of a Cottage Food Operation than of a Home Food Processing Establishment. Everywhere
-- else the state's single rule is written to each of its programs.
--
-- Four jurisdictions have NO labelling section in the source at all — Massachusetts, Montana,
-- Pennsylvania and Utah. They get a row with `notes` saying so and no requirements, which is the
-- honest record: "we don't know" is different from "nothing is required", and the generator refuses
-- to print rather than inventing a label.

set search_path = public;

-- A fixed vocabulary: a typo in an element name silently drops a required field off a label.
alter table public.state_label_rules
  add constraint state_label_rules_elements_known
    check (required_elements <@ array[
      'product_name', 'producer_name', 'business_name', 'producer_address', 'producer_phone',
      'producer_email', 'permit_number', 'municipality', 'ingredients_desc_by_weight',
      'net_weight', 'allergens', 'production_date', 'lot_code', 'nutrition_if_claimed'
    ]::text[]);

insert into public.state_label_rules (
  program_id, required_elements, disclaimer_text, disclaimer_min_pt, disclaimer_all_caps,
  disclaimer_font_note, metric_required, placard_required, placard_text, notes,
  source_url, source_checked_at
)
select
  fp.id, v.elements, v.disclaimer, v.min_pt, v.all_caps,
  v.font_note, v.metric, v.placard, v.placard_text, v.notes,
  fp.source_url, date '2026-09-04'
from (values
  ('AL', null, array['product_name','producer_name','producer_address','ingredients_desc_by_weight','allergens'], null, 10, false, null, false, false, null, 'Requires an allergen disclaimer and a statement that the food is not inspected by a health department; the source does not quote exact wording, so none is stored. All label text must be 10-point or larger.'),
  ('AK', null, array['permit_number','producer_name','producer_address','producer_phone'], null, null, false, null, false, true, 'THESE PRODUCTS ARE NOT SUBJECT TO STATE INSPECTION.', 'Either the Alaska business licence number OR the producer name, physical address and phone. The notice may be a card, placard, sign or label in a conspicuous area.'),
  ('AZ', null, array['business_name','permit_number','ingredients_desc_by_weight','production_date'], 'This product was produced in a home kitchen that may come in contact with common food allergens and pet allergens and is not subject to public health inspection.', null, false, null, false, false, null, 'Home address is not required since a 2019 rule change. The label must also carry the AZDHS website for reporting foodborne illness.'),
  ('AR', null, array['production_date','producer_name','producer_address','producer_phone','product_name','ingredients_desc_by_weight'], 'This product was produced in a private residence that is exempt from state licensing and inspection. This product may contain allergens.', null, false, null, false, false, null, 'A producer who does not want to publish their home address may use an identification number from the Arkansas Department of Agriculture instead of address and phone.'),
  ('CA', null, array['business_name','producer_address','permit_number','product_name','ingredients_desc_by_weight','allergens','net_weight'], 'Made in a Home Kitchen.', 12, false, null, false, false, null, null),
  ('CO', null, array['product_name','producer_name','producer_address','producer_phone','producer_email','production_date','ingredients_desc_by_weight'], 'This product was produced in a home kitchen that is not subject to state licensure or inspection and that may also contain common food allergies such as tree nuts, peanuts, eggs, soy, wheat, milk, fish, and crustacean shellfish. This product is not intended for resale.', null, false, null, false, false, null, 'The label must be in English.'),
  ('CT', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','net_weight','allergens'], 'Made in a Cottage Food Operation that is not Subject to Routine Government Food Safety Inspection.', 10, false, 'Clear and conspicuous. Hand-printed labels are acceptable if clearly legible.', true, false, null, null),
  ('DE', null, array['producer_name','producer_phone','producer_email','product_name','net_weight','production_date','allergens','ingredients_desc_by_weight'], 'This food is made in a Cottage Food Establishment and is NOT subject to routine Government Food Safety Inspections.', null, false, null, false, false, null, 'If the label is too small for the ingredient list, it must be available on request.'),
  ('DC', null, array['permit_number','product_name','ingredients_desc_by_weight','net_weight','allergens','nutrition_if_claimed'], 'Made by a cottage food business that is not subject to the District of Columbia''s food safety regulations.', 10, false, null, false, false, null, null),
  ('FL', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','net_weight','allergens','nutrition_if_claimed'], 'Made in a cottage food operation that is not subject to Florida''s food safety regulations.', 10, false, null, false, false, null, null),
  ('GA', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','allergens','net_weight'], 'MADE IN A COTTAGE FOOD OPERATION THAT IS NOT SUBJECT TO STATE FOOD SAFETY INSPECTIONS', 10, true, 'Times New Roman or Arial', false, false, null, 'Selling from bulk containers requires the same information on a sign or carriable notice at the point of sale.'),
  ('HI', null, array['product_name','ingredients_desc_by_weight','producer_name','producer_phone'], 'Made in a home kitchen not routinely inspected by the Department of Health.', null, false, null, false, false, null, 'Hand-pounded poi carries its own statement: "This hand-pounded poi was prepared in a facility not inspected by the Department of Health."'),
  ('ID', null, array['producer_phone','allergens'], null, null, false, null, false, true, 'Prepared in a home kitchen not subject to regulation and inspection by any regulatory authority.', 'Idaho accepts either a placard at the point of sale or a label on the packaging. The source paraphrases the wording rather than quoting it.'),
  ('IL', null, array['business_name','municipality','permit_number','product_name','ingredients_desc_by_weight','production_date','allergens'], 'This product was produced in a home kitchen not inspected by a health department that may also process common food allergens. If you have safety concerns, contact your local health department.', null, false, 'Prominent lettering', false, false, null, null),
  ('IN', null, array['producer_name','producer_address','production_date','product_name','net_weight','ingredients_desc_by_weight'], 'This product is home produced and processed and the production area has not been inspected by the State Department of Health.', 10, false, null, false, false, null, null),
  ('IA', 'Iowa Cottage Food', array['business_name','producer_address','product_name'], null, null, false, null, false, false, null, 'A Cottage Food Operation needs only a simple label: business name, business address and product name.'),
  ('IA', 'Iowa Home Food Processing Establishment', array['business_name','producer_address','product_name','ingredients_desc_by_weight','net_weight'], null, null, false, null, false, false, null, 'A Home Food Processing Establishment must add the ingredients and net amount.'),
  ('KS', null, array['product_name','producer_name','producer_address','ingredients_desc_by_weight','net_weight'], null, null, false, null, false, false, null, 'Quantity may be net weight, volume or count depending on the product. No disclaimer is required.'),
  ('KY', null, array['product_name','business_name','producer_address','ingredients_desc_by_weight','net_weight','production_date','allergens'], 'This product is home-produced and processed.', 10, false, null, false, false, null, null),
  ('LA', null, array[]::text[], null, null, false, null, false, false, null, 'Louisiana requires only a label clearly indicating that the food was not produced in a licensed or regulated facility. The statute is paraphrased in the source, so no exact wording is stored.'),
  ('ME', null, array['product_name','producer_address','ingredients_desc_by_weight','net_weight'], null, null, false, null, false, false, null, 'No label is required for products sold directly to consumers from home. These requirements apply to products sold anywhere else.'),
  ('MD', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','net_weight','allergens','nutrition_if_claimed'], 'Made by a cottage food business that is not subject to Maryland''s food safety regulations.', 10, false, null, false, false, null, 'A state-issued ID number may stand in for the name and address. Cottage food sold in retail outlets must also show the production date.'),
  ('MA', null, array[]::text[], null, null, false, null, false, false, null, 'The source has no labelling section for Massachusetts. Nothing is recorded here — check the state''s own guidance before printing a label.'),
  ('MI', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','net_weight','allergens'], 'Made in a home kitchen that has not been inspected by the Michigan Department of Agriculture & Rural Development.', 11, false, 'Hand-printed labels are acceptable if legible.', false, false, null, null),
  ('MN', null, array['producer_name','production_date','ingredients_desc_by_weight','allergens'], 'These products are homemade and not subject to state inspection.', null, false, null, false, true, 'These products are homemade and not subject to state inspection.', 'The same statement must also be displayed on a sign at the point of sale.'),
  ('MS', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','net_weight','allergens','nutrition_if_claimed'], 'Made in a Cottage Food operation that is not subject to Mississippi''s food safety regulations.', 10, false, null, false, false, null, null),
  ('MO', null, array['producer_name','producer_address','product_name','ingredients_desc_by_weight','net_weight'], null, null, false, null, false, true, 'Prepared in a kitchen that is not subject to inspection by the Missouri Department of Health and Senior Services.', 'The source paraphrases the label statement rather than quoting it. Honey producers are recommended to add: "Honey is not recommended for infants less than 12 months of age."'),
  ('MT', null, array[]::text[], null, null, false, null, false, false, null, 'The 2021 Local Food Choice Act exempts homemade food from labelling requirements, but producers must still make clear the food has not been licensed, permitted, certified, packaged, labelled or inspected under any official regulations.'),
  ('NE', null, array['producer_name','producer_address'], null, null, false, null, false, true, 'Prepared in a kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.', 'Nebraska requires a "clearly visible notification" rather than fixed label wording — and the same disclaimer must appear in any print, radio, television or internet advertising, which includes a storefront listing.'),
  ('NV', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight','allergens','net_weight'], 'MADE IN A COTTAGE FOOD OPERATION THAT IS NOT SUBJECT TO GOVERNMENT FOOD SAFETY INSPECTION.', null, true, 'Printed prominently', false, false, null, 'Craft food operators selling canned fruits and vegetables use: "MADE IN A CRAFT FOOD OPERATION THAT IS NOT SUBJECT TO GOVERNMENT FOOD SAFETY INSPECTION."'),
  ('NH', 'New Hampshire Exempt Home Food Operations', array['producer_name','producer_address','producer_phone','product_name','ingredients_desc_by_weight','allergens','lot_code'], 'This product is exempt from New Hampshire licensing and inspection.', 10, false, null, false, false, null, 'The product code must include the manufacture date, container size and lot or batch number to support a recall.'),
  ('NH', 'New Hampshire Homestead', array['producer_name','producer_address','producer_phone','product_name','ingredients_desc_by_weight','allergens','lot_code'], 'This product is made in a residential kitchen licensed by NH DHHS.', 10, false, null, false, false, null, 'Licensed producers carry a different disclaimer from exempt ones. The product code must include the manufacture date, container size and lot or batch number.'),
  ('NJ', null, array['product_name','ingredients_desc_by_weight','allergens','producer_name','business_name','permit_number','municipality'], 'This food is prepared pursuant to N.J.A.C. 8:24-11 in a home kitchen that has not been inspected by the Department of Health.', null, false, null, false, false, null, 'Allergens are declared with the word "Contains" followed by the list.'),
  ('NM', null, array['producer_phone','ingredients_desc_by_weight'], null, null, false, null, false, false, null, 'New Mexico requires a disclaimer that the food is home-produced and exempt from state licensing and inspection; the source paraphrases it rather than quoting exact wording.'),
  ('NY', null, array['product_name','ingredients_desc_by_weight','net_weight','producer_name','producer_address','allergens'], null, null, false, null, false, false, null, 'Allergens must be identified within the ingredient statement itself. No disclaimer is required.'),
  ('NC', null, array['product_name','business_name','producer_address','net_weight','ingredients_desc_by_weight'], null, null, false, null, true, false, null, 'Net weight must be given in ounces or pounds AND the gram equivalent.'),
  ('ND', null, array[]::text[], 'This product is made in a home kitchen that is not inspected by the state or local health department.', null, false, null, false, false, null, 'North Dakota requires only the statement.'),
  ('OH', null, array['product_name','business_name','producer_address','ingredients_desc_by_weight','net_weight','nutrition_if_claimed'], 'This product is home produced', 10, false, null, false, false, null, 'A baked good needing refrigeration must also carry "Keep Refrigerated".'),
  ('OK', null, array['producer_name','producer_phone','producer_address','product_name','ingredients_desc_by_weight','allergens'], 'This product was produced in a private residence that is exempt from government licensing and inspection.', null, false, null, false, false, null, 'Ingredients are listed in ASCENDING order of proportion, which is the opposite of most states. When someone other than the producer sells the food, the disclosure adds "This product may contain allergens." Food shipped across state lines must also meet federal labelling law.'),
  ('OR', null, array['producer_name','producer_phone','producer_address','permit_number','product_name','ingredients_desc_by_weight','net_weight','allergens','nutrition_if_claimed'], 'This product is homemade, is not prepared in an inspected food establishment and must be stored and displayed separately if merchandised by a retailer.', null, false, null, false, false, null, 'The label must also disclose the presence of pets in the dwelling and the potential for pet allergens. A unique identification number from the Department may stand in for the address.'),
  ('PA', null, array[]::text[], null, null, false, null, false, false, null, 'The source has no labelling section for Pennsylvania. Nothing is recorded here — check the state''s own guidance before printing a label.'),
  ('RI', null, array['ingredients_desc_by_weight','business_name','producer_address','producer_phone'], null, null, false, null, false, false, null, 'The source describes the rule for farmers selling homemade food; confirm it applies to the program you sell under.'),
  ('SC', null, array['business_name','producer_address','product_name','ingredients_desc_by_weight'], 'NOT FOR RESALE-PROCESSED AND PREPARED BY A HOME-BASED FOOD PRODUCTION OPERATION THAT IS NOT SUBJECT TO SOUTH CAROLINA''S FOOD SAFETY REGULATIONS.', null, true, 'Conspicuous, all capitals, in a colour that clearly contrasts with the background', false, false, null, null),
  ('SD', null, array['product_name','producer_name','producer_address','producer_phone','production_date','ingredients_desc_by_weight'], 'This product was not produced in a commercial kitchen. It has been home-processed in a kitchen that may also process common food allergens such as tree nuts, peanuts, eggs, soy, wheat, milk, fish, and crustacean shellfish.', null, false, null, false, false, null, null),
  ('TN', null, array['product_name','producer_name','producer_address','net_weight','ingredients_desc_by_weight','lot_code'], null, null, false, null, true, false, null, 'Quantity must be given in both Imperial and metric units. A lot number or date is required for traceability. Allergen labelling is recommended, not required. The 2017 amendment removed the not-inspected statement.'),
  ('TX', null, array['product_name','producer_address','business_name','allergens'], 'This food is made in a home kitchen and is not inspected by the Department of State Health Services or a local health department.', null, false, null, false, false, null, 'Frozen food must also carry, in 12-point or larger: "SAFE HANDLING INSTRUCTIONS: To prevent illness from bacteria, keep this food frozen until preparing for consumption".'),
  ('UT', null, array[]::text[], null, null, false, null, false, false, null, 'The source has no labelling section for Utah. Nothing is recorded here — check the state''s own guidance before printing a label.'),
  ('VT', null, array['producer_name','producer_address','product_name','net_weight','ingredients_desc_by_weight'], null, null, false, null, false, false, null, 'Quantity may be weight, volume or item count. The University of Vermont Extension publishes label guidelines.'),
  ('VA', null, array['producer_name','producer_address','producer_phone','production_date','product_name','net_weight','ingredients_desc_by_weight','nutrition_if_claimed'], 'NOT FOR RESALE - PROCESSED AND PREPARED WITHOUT STATE INSPECTION.', null, true, null, false, false, null, null),
  ('WA', null, array['business_name','permit_number','product_name','net_weight','ingredients_desc_by_weight'], 'Made in a home kitchen that has not been subject to standard inspection criteria.', 11, false, null, false, false, null, 'Quantity may be weight, volume or item count.'),
  ('WV', null, array['product_name','ingredients_desc_by_weight','producer_name','producer_address','producer_phone'], 'This product was produced at a private residence that is exempt from state licensing and inspection. This product may contain allergens.', null, false, null, false, false, null, null),
  ('WI', null, array['business_name','producer_address','product_name','production_date','allergens','ingredients_desc_by_weight'], 'This product was made in a private home not subject to state licensing or inspection.', null, false, null, false, false, null, 'The source words these as "should" rather than "must".'),
  ('WY', null, array[]::text[], 'This food was made in a home kitchen, is not regulated or inspected and may contain allergens.', null, false, null, false, false, null, 'No label is required for food sold directly to the end consumer. The disclaimer applies to food sold through retail outlets.')
) as v(
  state_code, program_name, elements, disclaimer, min_pt, all_caps,
  font_note, metric, placard, placard_text, notes
)
join public.state_food_programs fp
  on fp.state_code = v.state_code
 and (v.program_name is null or fp.name = v.program_name);
